version: "2.4"
services:

  mongo:
    image: mongo:6.0.2
    container_name: mongo
    healthcheck:
      test: ["CMD-SHELL", "mongosh --quiet localhost/test --eval 'quit(db.runCommand({ ping: 1 }).ok ? 0 : 2)'"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: esignbr/logistics
    container_name: logistics
    ports:
      - 8080:8080
    environment:
      - MONGODB_URI=mongodb://mongo/logistics
    depends_on:
      mongo:
        condition: service_healthy
