name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'microsoft'
        java-version: 11
        cache: 'maven'
    - uses: isbang/compose-action@v1.3.2
      with:
        compose-file: docker-compose.yml
    - name: Run API Test
      run: mvn test -Dserver.host=http://localhost -Dserver.port=8080
